name: CI

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Java 환경 설정 (JDK 17 사용)
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Gradle Wrapper에 실행 권한 부여
      - name: Grant execute permission to Gradle Wrapper
        run: chmod +x ./gradlew

      # 4. Gradle 빌드 수행
      - name: Build with Gradle
        run: ./gradlew clean build -x test --parallel
